version: "3.7"

services:
  main:
    build:
      context: .
      dockerfile: ./ops/images/go.Dockerfile
    depends_on:
      - db
    container_name: main
    ports:
      - 4000:4000
    env_file: ./.env
    environment:
      DB_URI: "${DB_URI}"
      ENV: "${ENV}"

  db:
    image: postgres:10.4
    container_name: db
    ports:
      - 5432:5432
    env_file: ./.env
    volumes:
      - ./db:/var/lib/postgresql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
