name: Push To Package Registry
on: [push]
jobs:
  publish_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Setup docker
        uses: docker-practice/actions-setup-docker@0.0.1

      - name: Publish to Registry
        env:
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
          REGISTRY_URL: ${{ secrets.DOCKER_REGISTRY_URL }}
        run: |
          docker login docker.pkg.github.com -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
          docker image build -t docker.pkg.github.com/atechnohazard/hades/hades:latest -f ./ops/images/go.Dockerfile .
          docker push docker.pkg.github.com/atechnohazard/hades/hades:latest